### ISSUE TITLE
1.3.1 - Reverse animation does not appear

### ISSUE THREAD

**Issue by shrmnk** [slooob/turbolinks-animate.js#2]
My site's init:
```coffee
document.addEventListener 'turbolinks:load', ->
  $('body').turbolinksAnimate({ animation: 'fadein', duration: '0.3s', delay: false })
  turbolinksAnimateAppear()

document.addEventListener 'turbolinks:request-start', ->
  turbolinksAnimateDisappear()

$(window).bind 'popstate', (event) ->
  turbolinksAnimateDisappear()
```

### Expected behavior
When clicking on the link, the page is expected to fade out before fading in the new page.

### Actual behavior
Page's fadeout animation does not happen, and jumps straight into fading in the next page

### Steps to reproduce
Click on a link

Note - this did not happen on version 1.2.0

**Comment by jonhue** [comment]
This should be fixed with 1.3.2
